// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: historyservice.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dnc.GrpcService.Protocol {

  /// <summary>Holder for reflection information generated from historyservice.proto</summary>
  public static partial class HistoryserviceReflection {

    #region Descriptor
    /// <summary>File descriptor for historyservice.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HistoryserviceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRoaXN0b3J5c2VydmljZS5wcm90bxIYZG5jLmdycGNTZXJ2aWNlLnByb3Rv",
            "Y29sIhkKC01lc3NhZ2VIZWFkEgoKAklQGAEgASgJIkYKD0dldEhpc3Rvcmll",
            "c1JlcRIzCgRIZWFkGAEgASgLMiUuZG5jLmdycGNTZXJ2aWNlLnByb3RvY29s",
            "Lk1lc3NhZ2VIZWFkIk4KB0hpc3RvcnkSCgoCSWQYASABKAUSEQoJU3RhcnRE",
            "YXRlGAIgASgJEg8KB0VuZERhdGUYAyABKAkSEwoLSGlzdG9yeU5hbWUYBCAB",
            "KAkiaQoPR2V0SGlzdG9yaWVzUnNwEg8KB1JldENvZGUYASABKAUSDwoHUmV0",
            "RGVzYxgCIAEoCRI0CglIaXN0b3JpZXMYAyADKAsyIS5kbmMuZ3JwY1NlcnZp",
            "Y2UucHJvdG9jb2wuSGlzdG9yeTJ4Cg5IaXN0b3J5U2VydmljZRJmCgxHZXRI",
            "aXN0b3JpZXMSKS5kbmMuZ3JwY1NlcnZpY2UucHJvdG9jb2wuR2V0SGlzdG9y",
            "aWVzUmVxGikuZG5jLmdycGNTZXJ2aWNlLnByb3RvY29sLkdldEhpc3Rvcmll",
            "c1JzcCIAQgJQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dnc.GrpcService.Protocol.MessageHead), global::Dnc.GrpcService.Protocol.MessageHead.Parser, new[]{ "IP" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dnc.GrpcService.Protocol.GetHistoriesReq), global::Dnc.GrpcService.Protocol.GetHistoriesReq.Parser, new[]{ "Head" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dnc.GrpcService.Protocol.History), global::Dnc.GrpcService.Protocol.History.Parser, new[]{ "Id", "StartDate", "EndDate", "HistoryName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dnc.GrpcService.Protocol.GetHistoriesRsp), global::Dnc.GrpcService.Protocol.GetHistoriesRsp.Parser, new[]{ "RetCode", "RetDesc", "Histories" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MessageHead : pb::IMessage<MessageHead> {
    private static readonly pb::MessageParser<MessageHead> _parser = new pb::MessageParser<MessageHead>(() => new MessageHead());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageHead> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dnc.GrpcService.Protocol.HistoryserviceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageHead() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageHead(MessageHead other) : this() {
      iP_ = other.iP_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageHead Clone() {
      return new MessageHead(this);
    }

    /// <summary>Field number for the "IP" field.</summary>
    public const int IPFieldNumber = 1;
    private string iP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IP {
      get { return iP_; }
      set {
        iP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageHead);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageHead other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IP != other.IP) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IP.Length != 0) hash ^= IP.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IP.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IP);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IP);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageHead other) {
      if (other == null) {
        return;
      }
      if (other.IP.Length != 0) {
        IP = other.IP;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            IP = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetHistoriesReq : pb::IMessage<GetHistoriesReq> {
    private static readonly pb::MessageParser<GetHistoriesReq> _parser = new pb::MessageParser<GetHistoriesReq>(() => new GetHistoriesReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetHistoriesReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dnc.GrpcService.Protocol.HistoryserviceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistoriesReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistoriesReq(GetHistoriesReq other) : this() {
      Head = other.head_ != null ? other.Head.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistoriesReq Clone() {
      return new GetHistoriesReq(this);
    }

    /// <summary>Field number for the "Head" field.</summary>
    public const int HeadFieldNumber = 1;
    private global::Dnc.GrpcService.Protocol.MessageHead head_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dnc.GrpcService.Protocol.MessageHead Head {
      get { return head_; }
      set {
        head_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetHistoriesReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetHistoriesReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Head, other.Head)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (head_ != null) hash ^= Head.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (head_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Head);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (head_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Head);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetHistoriesReq other) {
      if (other == null) {
        return;
      }
      if (other.head_ != null) {
        if (head_ == null) {
          head_ = new global::Dnc.GrpcService.Protocol.MessageHead();
        }
        Head.MergeFrom(other.Head);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (head_ == null) {
              head_ = new global::Dnc.GrpcService.Protocol.MessageHead();
            }
            input.ReadMessage(head_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class History : pb::IMessage<History> {
    private static readonly pb::MessageParser<History> _parser = new pb::MessageParser<History>(() => new History());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<History> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dnc.GrpcService.Protocol.HistoryserviceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public History() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public History(History other) : this() {
      id_ = other.id_;
      startDate_ = other.startDate_;
      endDate_ = other.endDate_;
      historyName_ = other.historyName_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public History Clone() {
      return new History(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "StartDate" field.</summary>
    public const int StartDateFieldNumber = 2;
    private string startDate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StartDate {
      get { return startDate_; }
      set {
        startDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EndDate" field.</summary>
    public const int EndDateFieldNumber = 3;
    private string endDate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EndDate {
      get { return endDate_; }
      set {
        endDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HistoryName" field.</summary>
    public const int HistoryNameFieldNumber = 4;
    private string historyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HistoryName {
      get { return historyName_; }
      set {
        historyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as History);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(History other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (StartDate != other.StartDate) return false;
      if (EndDate != other.EndDate) return false;
      if (HistoryName != other.HistoryName) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (StartDate.Length != 0) hash ^= StartDate.GetHashCode();
      if (EndDate.Length != 0) hash ^= EndDate.GetHashCode();
      if (HistoryName.Length != 0) hash ^= HistoryName.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (StartDate.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StartDate);
      }
      if (EndDate.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EndDate);
      }
      if (HistoryName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(HistoryName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (StartDate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartDate);
      }
      if (EndDate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndDate);
      }
      if (HistoryName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HistoryName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(History other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.StartDate.Length != 0) {
        StartDate = other.StartDate;
      }
      if (other.EndDate.Length != 0) {
        EndDate = other.EndDate;
      }
      if (other.HistoryName.Length != 0) {
        HistoryName = other.HistoryName;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            StartDate = input.ReadString();
            break;
          }
          case 26: {
            EndDate = input.ReadString();
            break;
          }
          case 34: {
            HistoryName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetHistoriesRsp : pb::IMessage<GetHistoriesRsp> {
    private static readonly pb::MessageParser<GetHistoriesRsp> _parser = new pb::MessageParser<GetHistoriesRsp>(() => new GetHistoriesRsp());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetHistoriesRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dnc.GrpcService.Protocol.HistoryserviceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistoriesRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistoriesRsp(GetHistoriesRsp other) : this() {
      retCode_ = other.retCode_;
      retDesc_ = other.retDesc_;
      histories_ = other.histories_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetHistoriesRsp Clone() {
      return new GetHistoriesRsp(this);
    }

    /// <summary>Field number for the "RetCode" field.</summary>
    public const int RetCodeFieldNumber = 1;
    private int retCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RetCode {
      get { return retCode_; }
      set {
        retCode_ = value;
      }
    }

    /// <summary>Field number for the "RetDesc" field.</summary>
    public const int RetDescFieldNumber = 2;
    private string retDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RetDesc {
      get { return retDesc_; }
      set {
        retDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Histories" field.</summary>
    public const int HistoriesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Dnc.GrpcService.Protocol.History> _repeated_histories_codec
        = pb::FieldCodec.ForMessage(26, global::Dnc.GrpcService.Protocol.History.Parser);
    private readonly pbc::RepeatedField<global::Dnc.GrpcService.Protocol.History> histories_ = new pbc::RepeatedField<global::Dnc.GrpcService.Protocol.History>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dnc.GrpcService.Protocol.History> Histories {
      get { return histories_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetHistoriesRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetHistoriesRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RetCode != other.RetCode) return false;
      if (RetDesc != other.RetDesc) return false;
      if(!histories_.Equals(other.histories_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RetCode != 0) hash ^= RetCode.GetHashCode();
      if (RetDesc.Length != 0) hash ^= RetDesc.GetHashCode();
      hash ^= histories_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RetCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RetCode);
      }
      if (RetDesc.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RetDesc);
      }
      histories_.WriteTo(output, _repeated_histories_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RetCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RetCode);
      }
      if (RetDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RetDesc);
      }
      size += histories_.CalculateSize(_repeated_histories_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetHistoriesRsp other) {
      if (other == null) {
        return;
      }
      if (other.RetCode != 0) {
        RetCode = other.RetCode;
      }
      if (other.RetDesc.Length != 0) {
        RetDesc = other.RetDesc;
      }
      histories_.Add(other.histories_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            RetCode = input.ReadInt32();
            break;
          }
          case 18: {
            RetDesc = input.ReadString();
            break;
          }
          case 26: {
            histories_.AddEntriesFrom(input, _repeated_histories_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
