// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dnc.GrpcService.Protocol {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEhhkbmMuZ3JwY1NlcnZpY2UucHJvdG9jb2waC21v",
            "ZGVsLnByb3RvMtoBCg5Ib2xpZGF5U2VydmljZRJjCgtHZXRIb2xpZGF5cxIo",
            "LmRuYy5ncnBjU2VydmljZS5wcm90b2NvbC5HZXRIb2xpZGF5c1JlcRooLmRu",
            "Yy5ncnBjU2VydmljZS5wcm90b2NvbC5HZXRIb2xpZGF5c1JzcCIAEmMKC0Fk",
            "ZEhvbGlkYXlzEiguZG5jLmdycGNTZXJ2aWNlLnByb3RvY29sLkFkZEhvbGlk",
            "YXlzUmVxGiguZG5jLmdycGNTZXJ2aWNlLnByb3RvY29sLkFkZEhvbGlkYXlz",
            "UnNwIgBCAlABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dnc.GrpcService.Protocol.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
